# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinador',
            name='id_solicitud',
        ),
        migrations.RemoveField(
            model_name='tecnico',
            name='id_solicitud',
        ),
        migrations.RemoveField(
            model_name='tecnico',
            name='id_visita',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='id_coordinador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poda.Coordinador'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='id_tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poda.Tecnico'),
        ),
        migrations.AddField(
            model_name='visita',
            name='id_tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poda.Tecnico'),
        ),
    ]
