# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poda', '0002_auto_20170324_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='id_solicitud',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
